config/routes.rb
Rails.application.routes.draw do
  resources :tokens

  resources :categories

  get 'stats' => "groups#stats"

  resources :groups do
  member do
    get "vote"
  end
end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'groups#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  validates_formatting_of :icon50, using: :url
  validates_formatting_of :icon, using: :url
  acts_as_votable 

  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_group, only: [:show, :edit, :update, :destroy, :vote]
  # before_filter :authenticate_user!

  def stats
    @close_group = Group.where(privacy: 'CLOSED').uniq.pluck(:gid).count
    @open_group = Group.where(privacy: 'OPEN').uniq.pluck(:gid).count
    @dupicate = Group.group(:gid).having("count(*) > 1").uniq.pluck(:gid).count(:gid)



# Iterate on each grouped item to destroy duplicate

  # @dupicate.each do |key, value|

  #   # Keep one and return rest of the duplicate records

  #   duplicates = Group.where(gid: key)[1..value-1]

  #   # puts "#{key} = #{duplicates.count}"

  #   # Destroy duplicates and their dependents

  #   duplicates.each(&:destroy)

  # end 


  end

  # GET /groups
  # GET /groups.json
  def index
    @q = Group.ransack(params[:q])
    @groups = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 20).order("created_at DESC")
    # @groups = Group.paginate(:page => params[:page], :per_page => 20).order("created_at DESC")
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
    
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.user = current_user

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  #->Prelang (voting/acts_as_votable)
  def vote

    direction = params[:direction]

    # Make sure we've specified a direction
    raise "No direction parameter specified to #vote action." unless direction

    # Make sure the direction is valid
    unless ["like", "bad"].member? direction
      raise "Direction '#{direction}' is not a valid direction for vote method."
    end

    @group.vote_by voter: current_user, vote: direction

    redirect_to action: :index
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:user_id, :gid, :name, :creator, :description, :privacy, :website, :email, :icon50, :icon)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for @group, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :gid, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :gid, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :creator, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :creator, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :description, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :privacy, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :privacy, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :website, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :website, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :email, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :icon50, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :icon50, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :icon, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :icon, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  groups_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/groups/edit.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Group %></h1>
</div>
<%= render :partial => 'form' %>

app/views/groups/index.html.erb
<%- model_class = Group -%>
<%= search_form_for @q do |f| %>
<div class="row">
  <div class="col-lg-12">
    <div class="input-group input-group-lg">
      <%= f.search_field :name_cont, class: "form-control", placeholder: "Search Group.." %>
      <span class="input-group-btn">
      <%= f.submit "Search", class: "btn btn-default" %>
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div><!-- /.row -->
<% end %>

<div class="page-header">
  <h1><%=t '.title', :default => Group %> <%= @groups.count %></h1>
</div>
<ul class="list-group">
<% @groups.each do |group| %>
  
    <li class="list-group-item">
    <%= image_tag group.icon50 %> <%= link_to group.name, "https://www.facebook.com/groups/#{group.gid}", target: "blank" %>
    <% if group.user == current_user %> <span class="pull-right"><%= link_to group_path(group), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
              <%= glyph 'info-sign' %>
              <%= glyph 'pencil' %>
            <%- end -%>
            <%= link_to group_path(group), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
              <%= glyph 'remove' %>
            <%- end -%></span><% end %>
    </li>
  
<% end %>
</ul>
<%= will_paginate @groups, renderer: BootstrapPagination::Rails %>

app/views/groups/new.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Group %></h1>
</div>
<%= render :partial => 'form' %>

app/views/groups/show.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => Group %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:gid) %></dt>
      <dd><pre class="prettyprint"><%= @group.gid %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @group.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:creator) %></dt>
      <dd><pre class="prettyprint"><%= @group.creator %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @group.description %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:privacy) %></dt>
      <dd><pre class="prettyprint"><%= @group.privacy %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:website) %></dt>
      <dd><pre class="prettyprint"><%= @group.website %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:email) %></dt>
      <dd><pre class="prettyprint"><%= @group.email %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:icon50) %></dt>
      <dd><pre class="prettyprint"><%= @group.icon50 %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:icon) %></dt>
      <dd><pre class="prettyprint"><%= @group.icon %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              groups_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_group_path(@group), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              group_path(@group),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/groups/stats.html.erb
<div class="row">
	<div class="col-md-6">
		<div class="panel panel-default">
		  <div class="panel-heading">
		    <h3 class="panel-title">Number Of Closed Group</h3>
		  </div>
		  <div class="panel-body">
		    <h1><%= @close_group %></h1>
		  </div>
		</div>
	</div>
	<div class="col-md-6">
		<div class="panel panel-default">
		  <div class="panel-heading">
		    <h3 class="panel-title">Number of Open Group</h3>
		  </div>
		  <div class="panel-body">
		    <h1><%= @open_group %></h1>
		  </div>
		</div>
		</div>
	</div>

</div>