config/routes.rb
Rails.application.routes.draw do
  resources :tokens

  resources :categories

  get 'stats' => "groups#stats"

  resources :groups do
  member do
    get "vote"
  end
end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'groups#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/token.rb
class Token < ActiveRecord::Base
end

app/controllers/tokens_controller.rb
class TokensController < InheritedResources::Base

  private

    def token_params
      params.require(:token).permit(:access_token)
    end
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/views/tokens/_form.html.erb
<%= simple_form_for(@token) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :access_token %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tokens/edit.html.erb
<h1>Editing token</h1>

<%= render 'form' %>

<%= link_to 'Show', @token %> |
<%= link_to 'Back', tokens_path %>

app/views/tokens/index.html.erb
<h1>Listing tokens</h1>

<table class="table">
  <thead>
    <tr>
      <th>Access token</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tokens.each do |token| %>
      <tr>
        <td><%= token.access_token %></td>
        <td><%= link_to 'Show', token %></td>
        <td><%= link_to 'Edit', edit_token_path(token) %></td>
        <td><%= link_to 'Destroy', token, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Token', new_token_path %>

app/views/tokens/new.html.erb
<h1>New token</h1>

<%= render 'form' %>

<%= link_to 'Back', tokens_path %>

app/views/tokens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Access token:</strong>
  <%= @token.access_token %>
</p>

<%= link_to 'Edit', edit_token_path(@token) %> |
<%= link_to 'Back', tokens_path %>